# Generated by Django 5.1 on 2024-09-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_table',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
