# Generated by Django 5.1 on 2024-09-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0002_alter_login_table_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_table',
            name='status',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
