# Generated by Django 5.1 on 2024-09-17 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0005_remove_product_table_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildmate.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='order_details_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=20)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildmate.product_table')),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildmate.order_table')),
            ],
        ),
    ]
