# Generated by Django 5.1 on 2024-09-19 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0006_order_table_order_details_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Offer_name', models.CharField(max_length=100)),
                ('Percentage', models.IntegerField(max_length=20)),
                ('From_date', models.DateField()),
                ('To_date', models.DateField()),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildmate.product_table')),
                ('SELLER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildmate.seller_table')),
            ],
        ),
    ]
