# Generated by Django 5.1 on 2024-09-19 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0007_offer_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='offer_table',
            old_name='Offer_name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='offer_table',
            name='PROMOTION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Buildmate.promotion'),
            preserve_default=False,
        ),
    ]
