# Generated by Django 5.1 on 2024-09-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0008_promotion_rename_offer_name_offer_table_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer_table',
            name='PROMOTION',
        ),
        migrations.DeleteModel(
            name='promotion',
        ),
    ]
