# Generated by Django 5.1 on 2024-09-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0009_remove_offer_table_promotion_delete_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='unit',
            field=models.CharField(default='per kg', max_length=50),
            preserve_default=False,
        ),
    ]
