# Generated by Django 5.1 on 2024-09-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0010_product_table_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer_table',
            name='SELLER',
        ),
    ]
