# Generated by Django 5.1 on 2024-09-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0011_remove_offer_table_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_table',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
