# Generated by Django 5.1 on 2024-09-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0012_offer_table_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_table',
            name='sale_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
