# Generated by Django 5.1 on 2024-09-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0015_product_table_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
