# Generated by Django 5.1 on 2024-09-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0016_product_table_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details_table',
            name='price',
            field=models.IntegerField(max_length=200),
        ),
    ]
