# Generated by Django 5.1 on 2024-10-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0018_alter_product_table_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
