# Generated by Django 5.1 on 2024-10-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0019_alter_product_table_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_table',
            name='Percentage',
            field=models.IntegerField(),
        ),
    ]
