# Generated by Django 5.1 on 2024-10-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0020_alter_offer_table_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_table',
            name='price',
            field=models.IntegerField(),
        ),
    ]
