# Generated by Django 5.1 on 2024-10-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0021_alter_product_table_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details_table',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product_table',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
