# Generated by Django 5.1 on 2024-10-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0022_alter_order_details_table_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_table',
            name='Percentage',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order_details_table',
            name='price',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product_table',
            name='price',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product_table',
            name='stock',
            field=models.IntegerField(max_length=20),
        ),
    ]
