# Generated by Django 5.1 on 2024-10-16 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0024_alter_product_table_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('houseNo', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=20)),
                ('landMark', models.CharField(max_length=100)),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildmate.order_table')),
            ],
        ),
    ]
