# Generated by Django 5.1 on 2024-10-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0025_delivery_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_table',
            name='Address',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
