# Generated by Django 5.1 on 2024-10-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0026_delivery_table_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_table',
            name='pin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery_table',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
