# Generated by Django 5.1 on 2024-10-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0027_delivery_table_pin_alter_delivery_table_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_details_table',
            name='price',
            field=models.FloatField(max_length=200),
        ),
    ]
