# Generated by Django 5.1 on 2024-10-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0029_alter_delivery_table_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_table',
            name='date',
            field=models.DateField(max_length=100),
        ),
    ]
