# Generated by Django 5.1 on 2024-10-27 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0030_alter_order_table_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('reply', models.CharField(max_length=200)),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildmate.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=200)),
                ('ratings', models.CharField(max_length=50)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildmate.product_table')),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildmate.user_table')),
            ],
        ),
    ]
