# Generated by Django 5.1 on 2024-10-27 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0031_complainttable_feedbacktable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacktable',
            name='PRODUCT',
        ),
        migrations.RemoveField(
            model_name='feedbacktable',
            name='USER_ID',
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.CharField(max_length=400)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=400)),
                ('USER', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Buildmate.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('feedback', models.CharField(max_length=20)),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildmate.order_details_table')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildmate.product_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buildmate.user_table')),
            ],
        ),
        migrations.DeleteModel(
            name='ComplaintTable',
        ),
        migrations.DeleteModel(
            name='FeedbackTable',
        ),
    ]
