# Generated by Django 5.1 on 2024-10-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0032_remove_feedbacktable_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='ORDER',
        ),
    ]
