# Generated by Django 5.1 on 2024-10-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0033_remove_feedback_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Rating',
            field=models.FloatField(default=4),
            preserve_default=False,
        ),
    ]
