# Generated by Django 5.1 on 2024-10-31 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buildmate', '0034_feedback_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.CharField(max_length=400)),
                ('date', models.DateField()),
                ('reply', models.CharField(max_length=400)),
                ('PRODUCT', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Buildmate.product_table')),
                ('USER', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Buildmate.user_table')),
            ],
        ),
    ]
